=== ppt000/mqttgateway/mqttgateway/gateway/mqtt_map_schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Map files for mqtt_gateways",
	"description": "",
	"definitions": {
	    "mapschema": {
			"description": "Data for map.",
			"type": "object",
			"properties": {
				"maptype": {
					"description": "Type of mapping, one of <none>, <loose> or <strict>",
					"type": "string",
					"enum": ["none", "loose", "strict"]
					},
				"map": {
					"description": "Actual map data in the form of <key: value> pair, MQTT keyword first.",
					"type": "object",
					"patternProperties": {".*": {"anyOf": [{"type": "string"},{"type": "null"}]}}
					}
				},
			"required": ["maptype"],
			"if": {"properties": {"maptype": {"enum": ["loose", "strict"]}}},
			"then": {"required": ["map"]}
			}
		},
	"type": "object",
	"properties": {
		"root": {
			"description": "Token to use at the beginning of every MQTT topic",
			"type": "string"
			},
		"topics": {
			"description": "List of topics to subscribe to.",
			"type": "array",
			"items": {"type": "string"}
			},
		"function": {"$ref": "#/definitions/mapschema"},
		"gateway": {"$ref": "#/definitions/mapschema"},
		"location": {"$ref": "#/definitions/mapschema"},
		"device": {"$ref": "#/definitions/mapschema"},
		"sender": {"$ref": "#/definitions/mapschema"},
		"action": {"$ref": "#/definitions/mapschema"},
		"argkey": {"$ref": "#/definitions/mapschema"},
		"argvalue": {"$ref": "#/definitions/mapschema"}
		},
	"required": ["root", "topics", "function", "gateway", "location",
		"device", "sender", "action", "argkey", "argvalue"]
}

=== ppt000/mqttgateway/tests/test_map.json
{
  "function": {
    "map": {
      "AudioVideo": [
        "audiovideo"
      ],
      "Lighting": [
        "lighting"
      ],
      "DummyFunction": [
        "dummyfunction"
      ]
    },
    "maptype": "loose"
  },
  "sender": {
    "maptype": "none"
  },
  "topics": [
    "home/+/dummy/+/+/+/C",
    "home/audiovideo/+/+/+/+/C"
  ],
  "action": {
    "map": {
      "POWER_ON": [
        "audio_on"
      ],
      "VOL_UP": [
        "volume_up"
      ],
      "SOURCE_CD": [
        "source_cd"
      ],
      "MUTE_TGL": [
        "mute_toggle"
      ],
      "POWER_OFF": [
        "audio_off"
      ],
      "MUTE_OFF": [
        "mute_off"
      ],
      "MUTE_ON": [
        "mute_on"
      ],
      "VOL_DN": [
        "volume_down"
      ],
      "SOURCE_TUNER": [
        "source_tuner"
      ],
      "LIGHT_OFF": [
        "light_off"
      ],
      "LIGHT_ON": [
        "light_on"
      ]
    },
    "maptype": "strict"
  },
  "location": {
    "map": {
      "DiningRm": [
        "dining_room"
      ],
      "Office": [
        "office"
      ],
      "Kitchen": [
        "kitchen"
      ]
    },
    "maptype": "loose"
  },
  "device": {
    "maptype": "none"
  },
  "argvalue": {
    "maptype": "none"
  },
  "root": "home",
  "gateway": {
    "map": {
      "Dummy": [
        "dummy"
      ]
    },
    "maptype": "strict"
  },
  "argkey": {
    "maptype": "none"
  }
}

=== ppt000/mqttgateway/mqttgateway/data/entry_map.json
{
	"root": "home",
	"topics": [
		"home/security/+/frontgarden/+/+/C",
		"home/+/entry2mqtt/+/+/+/C",
		"home/+/+/+/entrysystem/+/C"
	],
	"function": {
		"map": {
			"security": "Security",
			"lighting": "Lighting"
		},
		"maptype": "strict"
	},
	"gateway": {
		"map": {
			"entry2mqtt": "entry2mqtt"
		},
		"maptype": "strict"
	},
	"location": {
		"map": {
			"frontgarden": "gate_entry"
		},
		"maptype": "strict"
	},
	"device": {
		"map": {
			"gate": "Gate",
			"bell": "Bell"
		},
		"maptype": "strict"
	},
	"sender": {
		"maptype": "none"
	},
	"action": {
		"map": {
			"gate_open": "GATE_OPEN",
			"bell_off": "BELL_OFF",
			"bell_on": "BELL_ON",
			"light_off": "LIGHT_OFF",
			"light_on": "LIGHT_ON",
			"gate_close": "GATE_CLOSE"
		},
		"maptype": "strict"
	},
	"argkey": {
		"maptype": "none"
	},
	"argvalue": {
		"maptype": "none"
	}
}

=== ppt000/mqttgateway/entry/entry_map.json
{
	"function": {
		"map": {
			"Security": ["security"],
			"Lighting": ["lighting"]
		},
		"maptype": "strict"
	},
	"sender": {
		"maptype": "none"
	},
	"topics": ["home/security/+/frontgarden/+/+/C",
	"home/+/entry2mqtt/+/+/+/C",
	"home/+/+/+/entrysystem/+/C"],
	"action": {
		"map": {
			"GATE_OPEN": ["gate_open"],
			"BELL_OFF": ["bell_off"],
			"BELL_ON": ["bell_on"],
			"LIGHT_OFF": ["light_off"],
			"LIGHT_ON": ["light_on"],
			"GATE_CLOSE": ["gate_close"]
		},
		"maptype": "strict"
	},
	"location": {
		"map": {
			"gate_entry": ["frontgarden"]
		},
		"maptype": "strict"
	},
	"device": {
		"map": {
			"Gate": ["gate"],
			"Bell": ["bell"]
		},
		"maptype": "strict"
	},
	"argvalue": {
		"maptype": "none"
	},
	"root": "home",
	"gateway": {
		"map": {
			"entry2mqtt": ["entry2mqtt"]
		},
		"maptype": "strict"
	},
	"argkey": {
		"maptype": "none"
	}
}
